### ISSUE TITLE
Generating tweet_text from tweet_id

### ISSUE THREAD

**Issue by arijit1410** [nuhaalbadi/Arabic_hatespeech#1]
Hi,

I noticed that your dataset only contains the tweet_id. Could you suggest a method/library to convert the tweet_ids into its corresponding text?

**Comment by nuhaalbadi** [comment]
Hi there, 

we are only allowed to publicly share tweet ids along with its annotaion (1 = hate , 0 = not hate). Full tweets (except for those that have been deleted or made private) can be obtained by hydrating tweet ids using tools such as [twarc]( https://github.com/edsu/twarc).

**Comment by arijit1410** [comment]
Understood, thank you
